services:
  db:
    image: postgres:16-alpine
    container_name: lanchonete-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: lanchonete
      POSTGRES_PASSWORD: lanchonete
      POSTGRES_DB: lanchonete
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U lanchonete -d lanchonete']
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  pgdata:
